news_topic_research_task:
  description: >
    Identify the five most discussed news topics in the last 24 hours related to {topic}. 
    Ensure they are recent and come from reputable sources.
  agent: news_topic_researcher_agent
  expected_output: >
    A list of exactly five trending topics related to {topic}, each written on a separate line.

news_fetch_task:
  description: >
    Fetch top news stories & articles on given topics from past 24 hours,
  expected_output: >
    A list of top news stories & articles on given topics, each containing title, URL and a brief summary of each story
    in a JSON format.
  context: [news_topic_research_task]
  agent: news_fetcher_agent

news_analyzed_task:
  description: >
    Analyze each fetched news story, gather additional relevant information from the web, and ensure 
    there are at least 5 well-formatted articles. Each article must have a clear structure, with a 
    summary, key details, and an explanation of its significance.

    Use external sources to validate and expand on the content where needed.
  async_execution: True
  expected_output: >
    A well-structured markdown report analyzing each news article. Each analysis should include:

    - **Title**: The main headline of the article.
    - **Source & URL**: The original source and link to the full article.
    - **Summary**: A concise overview of the article in 2-3 sentences.
    - **Key Details**: Bullet points highlighting the most important aspects.
    - **Additional Insights**: Any extra relevant context from external sources.
    - **Why It Matters**: Explanation of the impact or significance of the news.

    **Markdown Format Example Output:**
    ```
    ## AI Breakthrough in Quantum Computing

    **🔗 Source:** [TechCrunch](https://example.com/article-link)

    **📌 Summary:**  
    Researchers have announced a significant breakthrough in quantum computing, achieving 
    a record-breaking qubit stability time...

    **📌 Key Details:**
    - Scientists at MIT developed a new error-correction method...
    - The new quantum chip can hold coherence for 10x longer...
    - Experts say this could lead to major advancements in AI processing...

    **📌 Additional Insights:**  
    - Other researchers from Stanford have confirmed similar findings...  
    - Industry analysts predict commercialization within the next 5 years...  

    **📌 Why It Matters:**  
    This breakthrough could revolutionize AI by enabling faster and more efficient computing power, 
    reducing energy costs, and advancing scientific research.
    ```

  context: [news_fetch_task]
  agent: news_analyzer_agent

news_edit_task:
  description: >
    Proofread, refine, and structure news articles into a polished markdown-formatted newsletter.
    Ensure grammatical accuracy, readability, and a well-organized layout that enhances engagement.
  expected_output: >
    A fully edited and structured markdown newsletter that includes:
    
    - **Headline Section** summarizing the top stories.
    - **Proofread & formatted news articles**, including:
      - **Title**: The main headline of the article.
      - **Source & URL**: The original source and a link to the full article.
      - **Summary**: A concise 2-3 sentence overview of the article.
      - **Key Details**: Bullet points highlighting crucial points.
      - **Why It Matters**: Explanation of its significance.
    - **Consistent markdown formatting** for readability.

    **Markdown Example Output:**
    ```
    # Top Stories in AI Today

    - AI takes spotlight in Super Bowl commercials  
    - Altman seeks TRILLIONS for global AI chip initiative  

    ## AI Takes Spotlight in Super Bowl Commercials

    **🔗 Source:** [TechCrunch](https://example.com/article-link)

    **📌 Summary:**  
    AI-powered commercials stole the show at this year’s Super Bowl, 
    featuring cutting-edge deepfake technology...

    **📌 Key Details:**
    - Several major brands integrated AI into their Super Bowl commercials.
    - AI-generated avatars were used to bring historical figures back to life.
    - Social media engagement saw a 200% spike in AI-related discussions.

    **📌 Why It Matters:**  
    The increasing use of AI in advertising signals a shift in consumer engagement,
    setting new industry standards for digital marketing.
    ```
  async_execution: False
  context: [news_analyzed_task]
  agent: news_editor_agent
  output_file: "final_newsletter.md"
