FROM python:3.12

LABEL maintainer="mahsaanabbasi@gmail.com"

WORKDIR /code

RUN apt-get update && apt-get install -y \
    build-essential \
    protobuf-compiler \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY ./pyproject.toml /code/
RUN poetry config virtualenvs.create false
RUN poetry config installer.max-workers 1

# Install dependencies without installing the current project
RUN poetry install --no-root

COPY . /code/

EXPOSE 8501

CMD [ "streamlit", "run", "./app/main.py" ]