venue_task:
  description: >
    Find a {venue_type} venue in {event_city} that meets criteria for {event_topic}/{event_description}.
  expected_output: >
    All the details of a specifically choosen venue you found to accommodate the event.
  agent: venue_coordinator

logistics_task:
  description: >
    Coordinate catering & equipment for an event with {expected_participants} participants on {tentative_date}.
  expected_output: >
    Confirmation of all logistics arrangments including catering & equipment setup
  agent: logistics_manager

marketing_task:
  description: >
    Promote the {event_topic}/{event_description} aiming to engage at least {expected_participants} potential attendees.
  expected_output: >
    Report on marketing activities & attendee engagement formatted as markdown.
  agent: marketing_communications_agent
