filter_emails:
  description: >
    Analyze a batch of emails and filter out
    non-essentional ones such as newsletter, promotional content and notifications

    Use your expertise in email content analysis to distinguish
    important emails from the rest, pay attention to the sender and avoind invalid emails.

    Make sure to filter for the messages actuallay directed at the user and avoid notifications

    emails: {emails}
  expected_output: >
    Your final answer MUST include the relevant thread_ids and the sender, use bullet points
  agent: email_filter_agent

action_required_emails:
  description: >
    For each email thread, pull and analyze the complete threads using only the 
    actual Thread ID. understanding the context, key points, and the overall sentiment
    of the converstion. Identify the main query or concerns that needs to be addressed
    in the response to the user.
  expected_output: >
    Your final answer MUST be a list for all emails with:
    - the thread_id
    - a summary of the email thread
    - a highlighting with the main points
    - identify the user and who he will be answering to 
    - communication style in the thread
    - the sender's email address.
  agent: email_action_agent

draft_responses:
  description: >
    Based on the action-required emails identified, draft responses foreach. Ensure that 
    each response is tailored to address the specific needs and context outlined in the email.

    - Assume the persona of the user and mimic the communication style in the thread.
    - Feel free to do research on the topic to provide a more detailed responses, IF NECESSARY.
    - If a research is necessary do it BEFORE drafting the response. 
    - If you need to pull the thread again do it using only the actual Thread ID.

    Use the tool provided to draft each of the responses.
    When using the tool pass the following input:
    - to (sender to be responded)
    - subject
    - messages

    You MUST create all drafts before sending your final answer.
    your final answer MUST be a confimation that all responses have been drafted.
  expected_output: >
    You MUST create all drafts before sending your final answer.
    Your final answer MUST be a confimation that all responses have been drafted.
  agent: email_response_writer